// src/App.js
import React, { useState } from "react";
import DashboardLayout from "./components/DashboardLayout";
import FileUploadForm from "./components/FileUploadForm";
import ResultsView from "./components/ResultsView";

function App() {
  const [results, setResults] = useState(null);
  const [activeTab, setActiveTab] = useState("1"); // 1: Upload, 2: Results, 3: Customer Summary, 4: Settings, (5: Newest Engagement)

  // When results are generated by the uploader, switch to Results tab
  const handleResults = (data) => {
    setResults(data);
    setActiveTab("2"); // go to Results tab
  };

  return (
    <DashboardLayout activeTab={activeTab} onTabChange={setActiveTab}>
      {/* Tab 1 — Upload & Generate (your uploader) */}
      {activeTab === "1" && <FileUploadForm setResults={handleResults} />}

      {/* Tab 2 — Results (auto-loads cached /analytics-last if no results passed) */}
      {activeTab === "2" && <ResultsView results={results} />}
      {activeTab === "3" && <h2>📊 Reports (Coming soon)</h2>}
      {activeTab === "4" && <h2>⚙️ Settings (Coming soon)</h2>}
    </DashboardLayout>
  );
}

export default App;
